# Generated by Django 5.0 on 2023-12-10 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=50)),
                ('d_email', models.EmailField(max_length=50)),
                ('d_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wig',
            fields=[
                ('wig_id', models.AutoField(primary_key=True, serialize=False)),
                ('wig_name', models.CharField(max_length=50)),
                ('wig_color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WigRecipient',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_name', models.CharField(max_length=255)),
                ('r_email', models.EmailField(max_length=50)),
                ('distribution_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistributionHistory',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('distribution_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.donor')),
                ('wig_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.wig')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.wigrecipient')),
            ],
        ),
    ]
