# Generated by Django 5.0 on 2024-01-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_donation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='image1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='image2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='image3',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
