# Generated by Django 5.0 on 2024-01-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_useraccount_password1'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='password2',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
